// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCrmApplet = "crm_applet"

// CrmApplet mapped from table <crm_applet>
type CrmApplet struct {
	Name       string    `gorm:"column:name;type:varchar(100);not null" json:"name"`
	Type       string    `gorm:"column:type;type:varchar(100);not null;default:up" json:"type"`
	CrmType    string    `gorm:"column:crm_type;type:varchar(100);not null;default:huke" json:"crm_type"`
	Appkey     string    `gorm:"column:appkey;type:varchar(100);not null" json:"appkey"`
	Appsecret  string    `gorm:"column:appsecret;type:varchar(100);not null" json:"appsecret"`
	Cid        string    `gorm:"column:cid;type:varchar(100);not null" json:"cid"`
	Status     string    `gorm:"column:status;type:varchar(100);not null;default:enable" json:"status"`                 // enable 启用  disable 禁用
	Createtime time.Time `gorm:"column:createtime;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"createtime"` // 创建时间
	Updatetime time.Time `gorm:"column:updatetime;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"updatetime"` // 修改时间
}

// TableName CrmApplet's table name
func (*CrmApplet) TableName() string {
	return TableNameCrmApplet
}
