// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUctModifyOrderAudit = "uct_modify_order_audit"

// UctModifyOrderAudit mapped from table <uct_modify_order_audit>
type UctModifyOrderAudit struct {
	ID         int64     `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	OrderID    int64     `gorm:"column:order_id;type:int;not null" json:"order_id"`                                     // 订单id
	DdAuditID  *string   `gorm:"column:dd_audit_id;type:varchar(100)" json:"dd_audit_id"`                               // 对应的钉钉审核id
	OrderType  int64     `gorm:"column:order_type;type:int;not null" json:"order_type"`                                 // 订单类型 0采购 1现买现卖 2销售 3送框
	AdminID    int64     `gorm:"column:admin_id;type:int;not null" json:"admin_id"`                                     // 发起人
	FieldList  *string   `gorm:"column:field_list;type:text" json:"field_list"`                                         // 字段列表
	Status     int64     `gorm:"column:status;type:tinyint;not null;default:1" json:"status"`                           // 状态  1待分部经理审核  2待运营经理审核  3待财务助理审核  4拒绝  5通过
	Createtime time.Time `gorm:"column:createtime;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"createtime"` // 创建时间
	Updatetime time.Time `gorm:"column:updatetime;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"updatetime"` // 修改时间
}

// TableName UctModifyOrderAudit's table name
func (*UctModifyOrderAudit) TableName() string {
	return TableNameUctModifyOrderAudit
}
