// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUctWasteCustomerGathering = "uct_waste_customer_gathering"

// UctWasteCustomerGathering mapped from table <uct_waste_customer_gathering>
type UctWasteCustomerGathering struct {
	ID             int64   `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"` // ID
	CustomerID     int64   `gorm:"column:customer_id;type:int unsigned;not null" json:"customer_id"`    // 客户ID
	Receiver       *string `gorm:"column:receiver;type:varchar(50)" json:"receiver"`                    // 收款人
	BankAccount    *string `gorm:"column:bank_account;type:varchar(50)" json:"bank_account"`            // 银行账号
	DepositBank    *string `gorm:"column:deposit_bank;type:varchar(100)" json:"deposit_bank"`           // 开户银行
	DepositAddress *string `gorm:"column:deposit_address;type:varchar(255)" json:"deposit_address"`     // 开户地址
	Createtime     *int64  `gorm:"column:createtime;type:int unsigned" json:"createtime"`               // 创建时间
	Updatetime     *int64  `gorm:"column:updatetime;type:int unsigned" json:"updatetime"`               // 更新时间
}

// TableName UctWasteCustomerGathering's table name
func (*UctWasteCustomerGathering) TableName() string {
	return TableNameUctWasteCustomerGathering
}
