// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUctCrmErpMap = "uct_crm_erp_map"

// UctCrmErpMap mapped from table <uct_crm_erp_map>
type UctCrmErpMap struct {
	ID           int64  `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id"`
	Crm          string `gorm:"column:crm;type:varchar(10);not null;default:ec" json:"crm"`  // 系统名称
	Type         string `gorm:"column:type;type:varchar(5);not null;default:up" json:"type"` // 客户类型
	FieldMap     string `gorm:"column:field_map;type:text;not null" json:"field_map"`
	CrmToErp     string `gorm:"column:crm_to_erp;type:text;not null" json:"crm_to_erp"`
	ErpToCrm     string `gorm:"column:erp_to_crm;type:text;not null" json:"erp_to_crm"`
	FieldMapLink string `gorm:"column:field_map_link;type:text;not null" json:"field_map_link"`
	CrmToErpLink string `gorm:"column:crm_to_erp_link;type:text;not null" json:"crm_to_erp_link"`
	ErpToCrmLink string `gorm:"column:erp_to_crm_link;type:text;not null" json:"erp_to_crm_link"`
}

// TableName UctCrmErpMap's table name
func (*UctCrmErpMap) TableName() string {
	return TableNameUctCrmErpMap
}
