// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUctAdmin = "uct_admin"

// UctAdmin mapped from table <uct_admin>
type UctAdmin struct {
	ID           int64   `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`    // ID
	BranchID     *int64  `gorm:"column:branch_id;type:int unsigned" json:"branch_id"`                    // 分部ID
	EcUserid     *int64  `gorm:"column:ec_userid;type:bigint unsigned" json:"ec_userid"`                 // ec员工id
	Crmid        *int64  `gorm:"column:crmid;type:bigint unsigned" json:"crmid"`                         // ec系统id
	EcLinkid     *string `gorm:"column:ec_linkid;type:varchar(100);default:0" json:"ec_linkid"`          // ec系统联系人id
	StaffAccid   *string `gorm:"column:staff_accid;type:varchar(100);default:0" json:"staff_accid"`      // 互客系统员工id
	CusAccid     *string `gorm:"column:cus_accid;type:varchar(100);default:0" json:"cus_accid"`          // 互客系统客户id
	LinkAccid    *string `gorm:"column:link_accid;type:varchar(100);default:0" json:"link_accid"`        // 互客系统客户联系人id
	Userid       *string `gorm:"column:userid;type:varchar(25)" json:"userid"`                           // 钉钉id
	WechatID     *string `gorm:"column:wechat_id;type:varchar(50)" json:"wechat_id"`                     // 企业微信id
	Username     string  `gorm:"column:username;type:varchar(20);not null" json:"username"`              // 用户名
	Nickname     string  `gorm:"column:nickname;type:varchar(50);not null" json:"nickname"`              // 昵称
	Password     string  `gorm:"column:password;type:varchar(32);not null" json:"password"`              // 密码
	Salt         string  `gorm:"column:salt;type:varchar(30);not null" json:"salt"`                      // 密码盐
	Avatar       string  `gorm:"column:avatar;type:varchar(100);not null" json:"avatar"`                 // 头像
	Mobile       *string `gorm:"column:mobile;type:varchar(30)" json:"mobile"`                           // 手机号
	Email        string  `gorm:"column:email;type:varchar(100);not null" json:"email"`                   // 电子邮箱
	Loginfailure int64   `gorm:"column:loginfailure;type:tinyint unsigned;not null" json:"loginfailure"` // 失败次数
	Logintime    int64   `gorm:"column:logintime;type:int unsigned;not null" json:"logintime"`           // 登录时间
	Createtime   int64   `gorm:"column:createtime;type:int unsigned;not null" json:"createtime"`         // 创建时间
	Updatetime   int64   `gorm:"column:updatetime;type:int unsigned;not null" json:"updatetime"`         // 更新时间
	Token        string  `gorm:"column:token;type:varchar(59);not null" json:"token"`                    // Session标识
	LastAppletid *string `gorm:"column:last_appletid;type:varchar(50)" json:"last_appletid"`             // 最近操作的应用标识
	Status       string  `gorm:"column:status;type:varchar(30);not null;default:normal" json:"status"`   // 状态 normal正常  hidden隐藏
}

// TableName UctAdmin's table name
func (*UctAdmin) TableName() string {
	return TableNameUctAdmin
}
