// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUctHuke = "uct_huke"

// UctHuke mapped from table <uct_huke>
type UctHuke struct {
	Name      string `gorm:"column:name;type:varchar(100);not null" json:"name"`
	Type      string `gorm:"column:type;type:varchar(100);not null;default:up" json:"type"`
	CrmType   string `gorm:"column:crm_type;type:varchar(100);not null;default:huke" json:"crm_type"`
	Appkey    string `gorm:"column:appkey;type:varchar(100);not null" json:"appkey"`
	Appsecret string `gorm:"column:appsecret;type:varchar(100);not null" json:"appsecret"`
	Cid       string `gorm:"column:cid;type:varchar(100);not null" json:"cid"`
	Status    string `gorm:"column:status;type:varchar(100);not null;default:enable" json:"status"` // enable 启用  disable 禁用
}

// TableName UctHuke's table name
func (*UctHuke) TableName() string {
	return TableNameUctHuke
}
