// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUctWasteCustomerFactory = "uct_waste_customer_factory"

// UctWasteCustomerFactory mapped from table <uct_waste_customer_factory>
type UctWasteCustomerFactory struct {
	ID            int64  `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`    // ID
	CustomerID    int64  `gorm:"column:customer_id;type:int unsigned;not null" json:"customer_id"`       // 客户ID
	Province      string `gorm:"column:province;type:varchar(50);not null" json:"province"`              // 省份
	City          string `gorm:"column:city;type:varchar(50);not null" json:"city"`                      // 城市
	Area          string `gorm:"column:area;type:varchar(50);not null" json:"area"`                      // 区域
	DetailAddress string `gorm:"column:detail_address;type:varchar(255);not null" json:"detail_address"` // 详细地址
	Linkman       string `gorm:"column:linkman;type:varchar(50);not null" json:"linkman"`                // 联系人
	Job           string `gorm:"column:job;type:varchar(50);not null" json:"job"`                        // 职务
	Mobile        string `gorm:"column:mobile;type:char(15);not null" json:"mobile"`                     // 联系电话
	Email         string `gorm:"column:email;type:varchar(50);not null" json:"email"`                    // 邮箱
	Adcode        int64  `gorm:"column:adcode;type:int;not null" json:"adcode"`                          // 行政区域编码
	Position      string `gorm:"column:position;type:varchar(255);not null;default:0,0" json:"position"` // 坐标点
	Createtime    *int64 `gorm:"column:createtime;type:int unsigned" json:"createtime"`                  // 创建时间
	Updatetime    *int64 `gorm:"column:updatetime;type:int unsigned" json:"updatetime"`                  // 更新时间
}

// TableName UctWasteCustomerFactory's table name
func (*UctWasteCustomerFactory) TableName() string {
	return TableNameUctWasteCustomerFactory
}
