// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUctWasteCustomer = "uct_waste_customer"

// UctWasteCustomer mapped from table <uct_waste_customer>
type UctWasteCustomer struct {
	ID                int64    `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true" json:"id"`                             // ID
	CusAccid          string   `gorm:"column:cus_accid;type:varchar(100);not null;default:0" json:"cus_accid"`                          // 互客系统id
	Crmid             string   `gorm:"column:crmid;type:varchar(100);not null;default:0" json:"crmid"`                                  // crmid
	AdminID           *string  `gorm:"column:admin_id;type:varchar(100)" json:"admin_id"`                                               // 客户账号ID
	BranchID          *int64   `gorm:"column:branch_id;type:int unsigned" json:"branch_id"`                                             // 分部ID
	Internal          *int64   `gorm:"column:internal;type:tinyint unsigned" json:"internal"`                                           // 内部客户 0否 1是
	GreenCoin         *int64   `gorm:"column:green_coin;type:int unsigned" json:"green_coin"`                                           // 绿币
	CustomerType      string   `gorm:"column:customer_type;type:enum('up','down');not null;default:up" json:"customer_type"`            // 客户类型:up=上游客户,down=下游客户
	CustomerCode      string   `gorm:"column:customer_code;type:varchar(100);not null" json:"customer_code"`                            // 客户编码
	Name              string   `gorm:"column:name;type:varchar(100);not null" json:"name"`                                              // 企业全称
	PrintTitleID      int64    `gorm:"column:print_title_id;type:int;not null;default:1" json:"print_title_id"`                         // 客户单据打印id
	NameEn            string   `gorm:"column:name_en;type:varchar(100);not null" json:"name_en"`                                        // 企业全称(英文)
	AllotID           int64    `gorm:"column:allot_id;type:int;not null" json:"allot_id"`                                               // 指定的分配人
	ManagerID         *int64   `gorm:"column:manager_id;type:int unsigned" json:"manager_id"`                                           // 业务负责人ID
	ServerID          *int64   `gorm:"column:server_id;type:int unsigned" json:"server_id"`                                             // 服务负责人ID
	SellerIncharge    *int64   `gorm:"column:seller_incharge;type:int unsigned" json:"seller_incharge"`                                 // 销售负责人ID
	ServiceDepartment int64    `gorm:"column:service_department;type:int unsigned;not null" json:"service_department"`                  // 服务部门 1 客服 2企服
	Incharge          string   `gorm:"column:incharge;type:varchar(50);not null" json:"incharge"`                                       // 客户负责人
	JuridicalPerson   string   `gorm:"column:juridical_person;type:varchar(50);not null" json:"juridical_person"`                       // 公司法人
	ClassA            string   `gorm:"column:class_a;type:varchar(20);not null" json:"class_a"`                                         // 客户类别a  A1 A2 A3 A4
	ClassB            string   `gorm:"column:class_b;type:varchar(20);not null" json:"class_b"`                                         // 客户类别b  B1 B2 B3 B4
	TradeType         *string  `gorm:"column:trade_type;type:varchar(5)" json:"trade_type"`                                             // 行业类型   1模切、涂布类 = M 特钢类 = T 隔膜类 = G 车废类 = C 其他类 = Q
	Mobile            string   `gorm:"column:mobile;type:char(15);not null" json:"mobile"`                                              // 联系电话
	WasteType         string   `gorm:"column:waste_type;type:varchar(100);not null" json:"waste_type"`                                  // 废料种类
	Level             *int64   `gorm:"column:level;type:int unsigned" json:"level"`                                                     // 客户级别
	CompanyAddress    *string  `gorm:"column:company_address;type:varchar(255)" json:"company_address"`                                 // 企业地址
	CompanyPosition   *string  `gorm:"column:company_position;type:text" json:"company_position"`                                       // 企业坐标
	Industry          *int64   `gorm:"column:industry;type:int unsigned" json:"industry"`                                               // 行业类别
	Website           *string  `gorm:"column:website;type:varchar(50)" json:"website"`                                                  // 官网
	SalesArea         *string  `gorm:"column:sales_area;type:varchar(50)" json:"sales_area"`                                            // 销售区域
	AnnualWaste       *float32 `gorm:"column:annual_waste;type:float unsigned" json:"annual_waste"`                                     // 年度废料量
	Detail            *string  `gorm:"column:detail;type:varchar(500)" json:"detail"`                                                   // 详情描述
	TaxCert           *string  `gorm:"column:tax_cert;type:varchar(50)" json:"tax_cert"`                                                // 税务登记证号
	TradingCert       *string  `gorm:"column:trading_cert;type:varchar(50)" json:"trading_cert"`                                        // 营业执照号
	CompanyNature     *int64   `gorm:"column:company_nature;type:int unsigned" json:"company_nature"`                                   // 企业性质
	TaxType           *int64   `gorm:"column:tax_type;type:int unsigned" json:"tax_type"`                                               // 税票类型
	SettleWay         *int64   `gorm:"column:settle_way;type:int unsigned" json:"settle_way"`                                           // 结算方式
	BackPercent       *int64   `gorm:"column:back_percent;type:int unsigned" json:"back_percent"`                                       // 分成比例(%)
	MonthReceivable   *int64   `gorm:"column:month_receivable;type:int unsigned" json:"month_receivable"`                               // 月结算服务 1是 0不是
	StatementsJSON    *string  `gorm:"column:statements_json;type:json" json:"statements_json"`                                         // 客户的结算基础资料（json格式）
	IsHideZero        int64    `gorm:"column:is_hide_zero;type:tinyint(1);not null" json:"is_hide_zero"`                                // 对账单是否屏蔽为零的项：0--不屏蔽     1--屏蔽
	IsSeparate        int64    `gorm:"column:is_separate;type:tinyint(1);not null" json:"is_separate"`                                  // 对账单是否收付款分离： 0--不分离    1--分离
	BlackState        *int64   `gorm:"column:black_state;type:int" json:"black_state"`                                                  // 重点关注客户
	State             string   `gorm:"column:state;type:enum('black','consult','draft','enabled');not null;default:draft" json:"state"` // 状态:black=黑名单,consult=客户咨询,draft=草稿,enabled=已提交
	Createtime        *int64   `gorm:"column:createtime;type:int unsigned" json:"createtime"`                                           // 创建时间
	Updatetime        *int64   `gorm:"column:updatetime;type:int unsigned" json:"updatetime"`                                           // 更新时间
}

// TableName UctWasteCustomer's table name
func (*UctWasteCustomer) TableName() string {
	return TableNameUctWasteCustomer
}
